[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  # Python yüklemeyi devre dışı bırak
  PIP_REQUIRE_VIRTUALENV = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

